name: Release

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version to deploy"
        required: true

jobs:
  binary:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Release
        uses: taiki-e/create-gh-release-action@d95ab4c4dc917cfa4a7cfc6468a0e5267ede79ac
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

      - name: Upload assets
        uses: taiki-e/upload-rust-binary-action@14950759bde99e9dbc62b33fff358f17d1542832
        with:
          bin: terraform-versions-tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          leading-dir: true
          target: ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""
